/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.ProductOrderNotification;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class EventType extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EventType\",\"namespace\":\"avro.ProductOrderNotification\",\"fields\":[{\"name\":\"productOrder\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"ProductOrderType\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"href\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"category\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"paymentApplicationId\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"state\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"priority\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"veeaId\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"vantivMID\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"notificationContact\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"promotionCode\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"description\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"riskCategory\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"transactionType\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"tokenId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"orderDate\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"completionDate\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"expectedCompletionDate\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"trackingNumber\",\"type\":[\"null\",\"string\"],\"default\":null}]}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public avro.ProductOrderNotification.ProductOrderType productOrder;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EventType() {}

  /**
   * All-args constructor.
   */
  public EventType(avro.ProductOrderNotification.ProductOrderType productOrder) {
    this.productOrder = productOrder;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return productOrder;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: productOrder = (avro.ProductOrderNotification.ProductOrderType)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'productOrder' field.
   */
  public avro.ProductOrderNotification.ProductOrderType getProductOrder() {
    return productOrder;
  }

  /**
   * Sets the value of the 'productOrder' field.
   * @param value the value to set.
   */
  public void setProductOrder(avro.ProductOrderNotification.ProductOrderType value) {
    this.productOrder = value;
  }

  /** Creates a new EventType RecordBuilder */
  public static avro.ProductOrderNotification.EventType.Builder newBuilder() {
    return new avro.ProductOrderNotification.EventType.Builder();
  }

  /** Creates a new EventType RecordBuilder by copying an existing Builder */
  public static avro.ProductOrderNotification.EventType.Builder newBuilder(avro.ProductOrderNotification.EventType.Builder other) {
    return new avro.ProductOrderNotification.EventType.Builder(other);
  }

  /** Creates a new EventType RecordBuilder by copying an existing EventType instance */
  public static avro.ProductOrderNotification.EventType.Builder newBuilder(avro.ProductOrderNotification.EventType other) {
    return new avro.ProductOrderNotification.EventType.Builder(other);
  }

  /**
   * RecordBuilder for EventType instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EventType>
    implements org.apache.avro.data.RecordBuilder<EventType> {

    private avro.ProductOrderNotification.ProductOrderType productOrder;

    /** Creates a new Builder */
    private Builder() {
      super(avro.ProductOrderNotification.EventType.SCHEMA$);
    }

    /** Creates a Builder by copying an existing Builder */
    private Builder(avro.ProductOrderNotification.EventType.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.productOrder)) {
        this.productOrder = data().deepCopy(fields()[0].schema(), other.productOrder);
        fieldSetFlags()[0] = true;
      }
    }

    /** Creates a Builder by copying an existing EventType instance */
    private Builder(avro.ProductOrderNotification.EventType other) {
            super(avro.ProductOrderNotification.EventType.SCHEMA$);
      if (isValidValue(fields()[0], other.productOrder)) {
        this.productOrder = data().deepCopy(fields()[0].schema(), other.productOrder);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'productOrder' field */
    public avro.ProductOrderNotification.ProductOrderType getProductOrder() {
      return productOrder;
    }

    /** Sets the value of the 'productOrder' field */
    public avro.ProductOrderNotification.EventType.Builder setProductOrder(avro.ProductOrderNotification.ProductOrderType value) {
      validate(fields()[0], value);
      this.productOrder = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /** Checks whether the 'productOrder' field has been set */
    public boolean hasProductOrder() {
      return fieldSetFlags()[0];
    }

    /** Clears the value of the 'productOrder' field */
    public avro.ProductOrderNotification.EventType.Builder clearProductOrder() {
      productOrder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public EventType build() {
      try {
        EventType record = new EventType();
        record.productOrder = fieldSetFlags()[0] ? this.productOrder : (avro.ProductOrderNotification.ProductOrderType) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
