/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.ProductOrderNotification;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ProductOrderType extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProductOrderType\",\"namespace\":\"avro.ProductOrderNotification\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"href\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"category\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"paymentApplicationId\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"state\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"priority\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"veeaId\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"vantivMID\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"notificationContact\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"promotionCode\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"description\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"riskCategory\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"transactionType\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"tokenId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"orderDate\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"completionDate\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"expectedCompletionDate\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"trackingNumber\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public CharSequence id;
  @Deprecated public CharSequence href;
  @Deprecated public CharSequence category;
  @Deprecated public Long paymentApplicationId;
  @Deprecated public CharSequence state;
  @Deprecated public Long priority;
  @Deprecated public Long veeaId;
  @Deprecated public CharSequence vantivMID;
  @Deprecated public CharSequence notificationContact;
  @Deprecated public CharSequence promotionCode;
  @Deprecated public CharSequence description;
  @Deprecated public CharSequence riskCategory;
  @Deprecated public CharSequence transactionType;
  @Deprecated public CharSequence tokenId;
  @Deprecated public CharSequence orderDate;
  @Deprecated public CharSequence completionDate;
  @Deprecated public CharSequence expectedCompletionDate;
  @Deprecated public CharSequence trackingNumber;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProductOrderType() {}

  /**
   * All-args constructor.
   */
  public ProductOrderType(CharSequence id, CharSequence href, CharSequence category, Long paymentApplicationId, CharSequence state, Long priority, Long veeaId, CharSequence vantivMID, CharSequence notificationContact, CharSequence promotionCode, CharSequence description, CharSequence riskCategory, CharSequence transactionType, CharSequence tokenId, CharSequence orderDate, CharSequence completionDate, CharSequence expectedCompletionDate, CharSequence trackingNumber) {
    this.id = id;
    this.href = href;
    this.category = category;
    this.paymentApplicationId = paymentApplicationId;
    this.state = state;
    this.priority = priority;
    this.veeaId = veeaId;
    this.vantivMID = vantivMID;
    this.notificationContact = notificationContact;
    this.promotionCode = promotionCode;
    this.description = description;
    this.riskCategory = riskCategory;
    this.transactionType = transactionType;
    this.tokenId = tokenId;
    this.orderDate = orderDate;
    this.completionDate = completionDate;
    this.expectedCompletionDate = expectedCompletionDate;
    this.trackingNumber = trackingNumber;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return href;
    case 2: return category;
    case 3: return paymentApplicationId;
    case 4: return state;
    case 5: return priority;
    case 6: return veeaId;
    case 7: return vantivMID;
    case 8: return notificationContact;
    case 9: return promotionCode;
    case 10: return description;
    case 11: return riskCategory;
    case 12: return transactionType;
    case 13: return tokenId;
    case 14: return orderDate;
    case 15: return completionDate;
    case 16: return expectedCompletionDate;
    case 17: return trackingNumber;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: id = (CharSequence)value$; break;
    case 1: href = (CharSequence)value$; break;
    case 2: category = (CharSequence)value$; break;
    case 3: paymentApplicationId = (Long)value$; break;
    case 4: state = (CharSequence)value$; break;
    case 5: priority = (Long)value$; break;
    case 6: veeaId = (Long)value$; break;
    case 7: vantivMID = (CharSequence)value$; break;
    case 8: notificationContact = (CharSequence)value$; break;
    case 9: promotionCode = (CharSequence)value$; break;
    case 10: description = (CharSequence)value$; break;
    case 11: riskCategory = (CharSequence)value$; break;
    case 12: transactionType = (CharSequence)value$; break;
    case 13: tokenId = (CharSequence)value$; break;
    case 14: orderDate = (CharSequence)value$; break;
    case 15: completionDate = (CharSequence)value$; break;
    case 16: expectedCompletionDate = (CharSequence)value$; break;
    case 17: trackingNumber = (CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'href' field.
   */
  public CharSequence getHref() {
    return href;
  }

  /**
   * Sets the value of the 'href' field.
   * @param value the value to set.
   */
  public void setHref(CharSequence value) {
    this.href = value;
  }

  /**
   * Gets the value of the 'category' field.
   */
  public CharSequence getCategory() {
    return category;
  }

  /**
   * Sets the value of the 'category' field.
   * @param value the value to set.
   */
  public void setCategory(CharSequence value) {
    this.category = value;
  }

  /**
   * Gets the value of the 'paymentApplicationId' field.
   */
  public Long getPaymentApplicationId() {
    return paymentApplicationId;
  }

  /**
   * Sets the value of the 'paymentApplicationId' field.
   * @param value the value to set.
   */
  public void setPaymentApplicationId(Long value) {
    this.paymentApplicationId = value;
  }

  /**
   * Gets the value of the 'state' field.
   */
  public CharSequence getState() {
    return state;
  }

  /**
   * Sets the value of the 'state' field.
   * @param value the value to set.
   */
  public void setState(CharSequence value) {
    this.state = value;
  }

  /**
   * Gets the value of the 'priority' field.
   */
  public Long getPriority() {
    return priority;
  }

  /**
   * Sets the value of the 'priority' field.
   * @param value the value to set.
   */
  public void setPriority(Long value) {
    this.priority = value;
  }

  /**
   * Gets the value of the 'veeaId' field.
   */
  public Long getVeeaId() {
    return veeaId;
  }

  /**
   * Sets the value of the 'veeaId' field.
   * @param value the value to set.
   */
  public void setVeeaId(Long value) {
    this.veeaId = value;
  }

  /**
   * Gets the value of the 'vantivMID' field.
   */
  public CharSequence getVantivMID() {
    return vantivMID;
  }

  /**
   * Sets the value of the 'vantivMID' field.
   * @param value the value to set.
   */
  public void setVantivMID(CharSequence value) {
    this.vantivMID = value;
  }

  /**
   * Gets the value of the 'notificationContact' field.
   */
  public CharSequence getNotificationContact() {
    return notificationContact;
  }

  /**
   * Sets the value of the 'notificationContact' field.
   * @param value the value to set.
   */
  public void setNotificationContact(CharSequence value) {
    this.notificationContact = value;
  }

  /**
   * Gets the value of the 'promotionCode' field.
   */
  public CharSequence getPromotionCode() {
    return promotionCode;
  }

  /**
   * Sets the value of the 'promotionCode' field.
   * @param value the value to set.
   */
  public void setPromotionCode(CharSequence value) {
    this.promotionCode = value;
  }

  /**
   * Gets the value of the 'description' field.
   */
  public CharSequence getDescription() {
    return description;
  }

  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(CharSequence value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'riskCategory' field.
   */
  public CharSequence getRiskCategory() {
    return riskCategory;
  }

  /**
   * Sets the value of the 'riskCategory' field.
   * @param value the value to set.
   */
  public void setRiskCategory(CharSequence value) {
    this.riskCategory = value;
  }

  /**
   * Gets the value of the 'transactionType' field.
   */
  public CharSequence getTransactionType() {
    return transactionType;
  }

  /**
   * Sets the value of the 'transactionType' field.
   * @param value the value to set.
   */
  public void setTransactionType(CharSequence value) {
    this.transactionType = value;
  }

  /**
   * Gets the value of the 'tokenId' field.
   */
  public CharSequence getTokenId() {
    return tokenId;
  }

  /**
   * Sets the value of the 'tokenId' field.
   * @param value the value to set.
   */
  public void setTokenId(CharSequence value) {
    this.tokenId = value;
  }

  /**
   * Gets the value of the 'orderDate' field.
   */
  public CharSequence getOrderDate() {
    return orderDate;
  }

  /**
   * Sets the value of the 'orderDate' field.
   * @param value the value to set.
   */
  public void setOrderDate(CharSequence value) {
    this.orderDate = value;
  }

  /**
   * Gets the value of the 'completionDate' field.
   */
  public CharSequence getCompletionDate() {
    return completionDate;
  }

  /**
   * Sets the value of the 'completionDate' field.
   * @param value the value to set.
   */
  public void setCompletionDate(CharSequence value) {
    this.completionDate = value;
  }

  /**
   * Gets the value of the 'expectedCompletionDate' field.
   */
  public CharSequence getExpectedCompletionDate() {
    return expectedCompletionDate;
  }

  /**
   * Sets the value of the 'expectedCompletionDate' field.
   * @param value the value to set.
   */
  public void setExpectedCompletionDate(CharSequence value) {
    this.expectedCompletionDate = value;
  }

  /**
   * Gets the value of the 'trackingNumber' field.
   */
  public CharSequence getTrackingNumber() {
    return trackingNumber;
  }

  /**
   * Sets the value of the 'trackingNumber' field.
   * @param value the value to set.
   */
  public void setTrackingNumber(CharSequence value) {
    this.trackingNumber = value;
  }

  /** Creates a new ProductOrderType RecordBuilder */
  public static avro.ProductOrderNotification.ProductOrderType.Builder newBuilder() {
    return new avro.ProductOrderNotification.ProductOrderType.Builder();
  }

  /** Creates a new ProductOrderType RecordBuilder by copying an existing Builder */
  public static avro.ProductOrderNotification.ProductOrderType.Builder newBuilder(avro.ProductOrderNotification.ProductOrderType.Builder other) {
    return new avro.ProductOrderNotification.ProductOrderType.Builder(other);
  }

  /** Creates a new ProductOrderType RecordBuilder by copying an existing ProductOrderType instance */
  public static avro.ProductOrderNotification.ProductOrderType.Builder newBuilder(avro.ProductOrderNotification.ProductOrderType other) {
    return new avro.ProductOrderNotification.ProductOrderType.Builder(other);
  }

  /**
   * RecordBuilder for ProductOrderType instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProductOrderType>
    implements org.apache.avro.data.RecordBuilder<ProductOrderType> {

    private CharSequence id;
    private CharSequence href;
    private CharSequence category;
    private Long paymentApplicationId;
    private CharSequence state;
    private Long priority;
    private Long veeaId;
    private CharSequence vantivMID;
    private CharSequence notificationContact;
    private CharSequence promotionCode;
    private CharSequence description;
    private CharSequence riskCategory;
    private CharSequence transactionType;
    private CharSequence tokenId;
    private CharSequence orderDate;
    private CharSequence completionDate;
    private CharSequence expectedCompletionDate;
    private CharSequence trackingNumber;

    /** Creates a new Builder */
    private Builder() {
      super(avro.ProductOrderNotification.ProductOrderType.SCHEMA$);
    }

    /** Creates a Builder by copying an existing Builder */
    private Builder(avro.ProductOrderNotification.ProductOrderType.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.href)) {
        this.href = data().deepCopy(fields()[1].schema(), other.href);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.category)) {
        this.category = data().deepCopy(fields()[2].schema(), other.category);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.paymentApplicationId)) {
        this.paymentApplicationId = data().deepCopy(fields()[3].schema(), other.paymentApplicationId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.state)) {
        this.state = data().deepCopy(fields()[4].schema(), other.state);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.priority)) {
        this.priority = data().deepCopy(fields()[5].schema(), other.priority);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.veeaId)) {
        this.veeaId = data().deepCopy(fields()[6].schema(), other.veeaId);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.vantivMID)) {
        this.vantivMID = data().deepCopy(fields()[7].schema(), other.vantivMID);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.notificationContact)) {
        this.notificationContact = data().deepCopy(fields()[8].schema(), other.notificationContact);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.promotionCode)) {
        this.promotionCode = data().deepCopy(fields()[9].schema(), other.promotionCode);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.description)) {
        this.description = data().deepCopy(fields()[10].schema(), other.description);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.riskCategory)) {
        this.riskCategory = data().deepCopy(fields()[11].schema(), other.riskCategory);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.transactionType)) {
        this.transactionType = data().deepCopy(fields()[12].schema(), other.transactionType);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.tokenId)) {
        this.tokenId = data().deepCopy(fields()[13].schema(), other.tokenId);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.orderDate)) {
        this.orderDate = data().deepCopy(fields()[14].schema(), other.orderDate);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.completionDate)) {
        this.completionDate = data().deepCopy(fields()[15].schema(), other.completionDate);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.expectedCompletionDate)) {
        this.expectedCompletionDate = data().deepCopy(fields()[16].schema(), other.expectedCompletionDate);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.trackingNumber)) {
        this.trackingNumber = data().deepCopy(fields()[17].schema(), other.trackingNumber);
        fieldSetFlags()[17] = true;
      }
    }

    /** Creates a Builder by copying an existing ProductOrderType instance */
    private Builder(avro.ProductOrderNotification.ProductOrderType other) {
            super(avro.ProductOrderNotification.ProductOrderType.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.href)) {
        this.href = data().deepCopy(fields()[1].schema(), other.href);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.category)) {
        this.category = data().deepCopy(fields()[2].schema(), other.category);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.paymentApplicationId)) {
        this.paymentApplicationId = data().deepCopy(fields()[3].schema(), other.paymentApplicationId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.state)) {
        this.state = data().deepCopy(fields()[4].schema(), other.state);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.priority)) {
        this.priority = data().deepCopy(fields()[5].schema(), other.priority);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.veeaId)) {
        this.veeaId = data().deepCopy(fields()[6].schema(), other.veeaId);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.vantivMID)) {
        this.vantivMID = data().deepCopy(fields()[7].schema(), other.vantivMID);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.notificationContact)) {
        this.notificationContact = data().deepCopy(fields()[8].schema(), other.notificationContact);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.promotionCode)) {
        this.promotionCode = data().deepCopy(fields()[9].schema(), other.promotionCode);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.description)) {
        this.description = data().deepCopy(fields()[10].schema(), other.description);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.riskCategory)) {
        this.riskCategory = data().deepCopy(fields()[11].schema(), other.riskCategory);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.transactionType)) {
        this.transactionType = data().deepCopy(fields()[12].schema(), other.transactionType);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.tokenId)) {
        this.tokenId = data().deepCopy(fields()[13].schema(), other.tokenId);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.orderDate)) {
        this.orderDate = data().deepCopy(fields()[14].schema(), other.orderDate);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.completionDate)) {
        this.completionDate = data().deepCopy(fields()[15].schema(), other.completionDate);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.expectedCompletionDate)) {
        this.expectedCompletionDate = data().deepCopy(fields()[16].schema(), other.expectedCompletionDate);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.trackingNumber)) {
        this.trackingNumber = data().deepCopy(fields()[17].schema(), other.trackingNumber);
        fieldSetFlags()[17] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public CharSequence getId() {
      return id;
    }

    /** Sets the value of the 'id' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder setId(CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }

    /** Clears the value of the 'id' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'href' field */
    public CharSequence getHref() {
      return href;
    }

    /** Sets the value of the 'href' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder setHref(CharSequence value) {
      validate(fields()[1], value);
      this.href = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /** Checks whether the 'href' field has been set */
    public boolean hasHref() {
      return fieldSetFlags()[1];
    }

    /** Clears the value of the 'href' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder clearHref() {
      href = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'category' field */
    public CharSequence getCategory() {
      return category;
    }

    /** Sets the value of the 'category' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder setCategory(CharSequence value) {
      validate(fields()[2], value);
      this.category = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /** Checks whether the 'category' field has been set */
    public boolean hasCategory() {
      return fieldSetFlags()[2];
    }

    /** Clears the value of the 'category' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder clearCategory() {
      category = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'paymentApplicationId' field */
    public Long getPaymentApplicationId() {
      return paymentApplicationId;
    }

    /** Sets the value of the 'paymentApplicationId' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder setPaymentApplicationId(Long value) {
      validate(fields()[3], value);
      this.paymentApplicationId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /** Checks whether the 'paymentApplicationId' field has been set */
    public boolean hasPaymentApplicationId() {
      return fieldSetFlags()[3];
    }

    /** Clears the value of the 'paymentApplicationId' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder clearPaymentApplicationId() {
      paymentApplicationId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'state' field */
    public CharSequence getState() {
      return state;
    }

    /** Sets the value of the 'state' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder setState(CharSequence value) {
      validate(fields()[4], value);
      this.state = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /** Checks whether the 'state' field has been set */
    public boolean hasState() {
      return fieldSetFlags()[4];
    }

    /** Clears the value of the 'state' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder clearState() {
      state = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'priority' field */
    public Long getPriority() {
      return priority;
    }

    /** Sets the value of the 'priority' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder setPriority(Long value) {
      validate(fields()[5], value);
      this.priority = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /** Checks whether the 'priority' field has been set */
    public boolean hasPriority() {
      return fieldSetFlags()[5];
    }

    /** Clears the value of the 'priority' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder clearPriority() {
      priority = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'veeaId' field */
    public Long getVeeaId() {
      return veeaId;
    }

    /** Sets the value of the 'veeaId' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder setVeeaId(Long value) {
      validate(fields()[6], value);
      this.veeaId = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /** Checks whether the 'veeaId' field has been set */
    public boolean hasVeeaId() {
      return fieldSetFlags()[6];
    }

    /** Clears the value of the 'veeaId' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder clearVeeaId() {
      veeaId = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'vantivMID' field */
    public CharSequence getVantivMID() {
      return vantivMID;
    }

    /** Sets the value of the 'vantivMID' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder setVantivMID(CharSequence value) {
      validate(fields()[7], value);
      this.vantivMID = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /** Checks whether the 'vantivMID' field has been set */
    public boolean hasVantivMID() {
      return fieldSetFlags()[7];
    }

    /** Clears the value of the 'vantivMID' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder clearVantivMID() {
      vantivMID = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'notificationContact' field */
    public CharSequence getNotificationContact() {
      return notificationContact;
    }

    /** Sets the value of the 'notificationContact' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder setNotificationContact(CharSequence value) {
      validate(fields()[8], value);
      this.notificationContact = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /** Checks whether the 'notificationContact' field has been set */
    public boolean hasNotificationContact() {
      return fieldSetFlags()[8];
    }

    /** Clears the value of the 'notificationContact' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder clearNotificationContact() {
      notificationContact = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'promotionCode' field */
    public CharSequence getPromotionCode() {
      return promotionCode;
    }

    /** Sets the value of the 'promotionCode' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder setPromotionCode(CharSequence value) {
      validate(fields()[9], value);
      this.promotionCode = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /** Checks whether the 'promotionCode' field has been set */
    public boolean hasPromotionCode() {
      return fieldSetFlags()[9];
    }

    /** Clears the value of the 'promotionCode' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder clearPromotionCode() {
      promotionCode = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'description' field */
    public CharSequence getDescription() {
      return description;
    }

    /** Sets the value of the 'description' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder setDescription(CharSequence value) {
      validate(fields()[10], value);
      this.description = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /** Checks whether the 'description' field has been set */
    public boolean hasDescription() {
      return fieldSetFlags()[10];
    }

    /** Clears the value of the 'description' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder clearDescription() {
      description = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'riskCategory' field */
    public CharSequence getRiskCategory() {
      return riskCategory;
    }

    /** Sets the value of the 'riskCategory' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder setRiskCategory(CharSequence value) {
      validate(fields()[11], value);
      this.riskCategory = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /** Checks whether the 'riskCategory' field has been set */
    public boolean hasRiskCategory() {
      return fieldSetFlags()[11];
    }

    /** Clears the value of the 'riskCategory' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder clearRiskCategory() {
      riskCategory = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'transactionType' field */
    public CharSequence getTransactionType() {
      return transactionType;
    }

    /** Sets the value of the 'transactionType' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder setTransactionType(CharSequence value) {
      validate(fields()[12], value);
      this.transactionType = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /** Checks whether the 'transactionType' field has been set */
    public boolean hasTransactionType() {
      return fieldSetFlags()[12];
    }

    /** Clears the value of the 'transactionType' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder clearTransactionType() {
      transactionType = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'tokenId' field */
    public CharSequence getTokenId() {
      return tokenId;
    }

    /** Sets the value of the 'tokenId' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder setTokenId(CharSequence value) {
      validate(fields()[13], value);
      this.tokenId = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /** Checks whether the 'tokenId' field has been set */
    public boolean hasTokenId() {
      return fieldSetFlags()[13];
    }

    /** Clears the value of the 'tokenId' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder clearTokenId() {
      tokenId = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'orderDate' field */
    public CharSequence getOrderDate() {
      return orderDate;
    }

    /** Sets the value of the 'orderDate' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder setOrderDate(CharSequence value) {
      validate(fields()[14], value);
      this.orderDate = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /** Checks whether the 'orderDate' field has been set */
    public boolean hasOrderDate() {
      return fieldSetFlags()[14];
    }

    /** Clears the value of the 'orderDate' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder clearOrderDate() {
      orderDate = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'completionDate' field */
    public CharSequence getCompletionDate() {
      return completionDate;
    }

    /** Sets the value of the 'completionDate' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder setCompletionDate(CharSequence value) {
      validate(fields()[15], value);
      this.completionDate = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /** Checks whether the 'completionDate' field has been set */
    public boolean hasCompletionDate() {
      return fieldSetFlags()[15];
    }

    /** Clears the value of the 'completionDate' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder clearCompletionDate() {
      completionDate = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /** Gets the value of the 'expectedCompletionDate' field */
    public CharSequence getExpectedCompletionDate() {
      return expectedCompletionDate;
    }

    /** Sets the value of the 'expectedCompletionDate' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder setExpectedCompletionDate(CharSequence value) {
      validate(fields()[16], value);
      this.expectedCompletionDate = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /** Checks whether the 'expectedCompletionDate' field has been set */
    public boolean hasExpectedCompletionDate() {
      return fieldSetFlags()[16];
    }

    /** Clears the value of the 'expectedCompletionDate' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder clearExpectedCompletionDate() {
      expectedCompletionDate = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /** Gets the value of the 'trackingNumber' field */
    public CharSequence getTrackingNumber() {
      return trackingNumber;
    }

    /** Sets the value of the 'trackingNumber' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder setTrackingNumber(CharSequence value) {
      validate(fields()[17], value);
      this.trackingNumber = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /** Checks whether the 'trackingNumber' field has been set */
    public boolean hasTrackingNumber() {
      return fieldSetFlags()[17];
    }

    /** Clears the value of the 'trackingNumber' field */
    public avro.ProductOrderNotification.ProductOrderType.Builder clearTrackingNumber() {
      trackingNumber = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    @Override
    public ProductOrderType build() {
      try {
        ProductOrderType record = new ProductOrderType();
        record.id = fieldSetFlags()[0] ? this.id : (CharSequence) defaultValue(fields()[0]);
        record.href = fieldSetFlags()[1] ? this.href : (CharSequence) defaultValue(fields()[1]);
        record.category = fieldSetFlags()[2] ? this.category : (CharSequence) defaultValue(fields()[2]);
        record.paymentApplicationId = fieldSetFlags()[3] ? this.paymentApplicationId : (Long) defaultValue(fields()[3]);
        record.state = fieldSetFlags()[4] ? this.state : (CharSequence) defaultValue(fields()[4]);
        record.priority = fieldSetFlags()[5] ? this.priority : (Long) defaultValue(fields()[5]);
        record.veeaId = fieldSetFlags()[6] ? this.veeaId : (Long) defaultValue(fields()[6]);
        record.vantivMID = fieldSetFlags()[7] ? this.vantivMID : (CharSequence) defaultValue(fields()[7]);
        record.notificationContact = fieldSetFlags()[8] ? this.notificationContact : (CharSequence) defaultValue(fields()[8]);
        record.promotionCode = fieldSetFlags()[9] ? this.promotionCode : (CharSequence) defaultValue(fields()[9]);
        record.description = fieldSetFlags()[10] ? this.description : (CharSequence) defaultValue(fields()[10]);
        record.riskCategory = fieldSetFlags()[11] ? this.riskCategory : (CharSequence) defaultValue(fields()[11]);
        record.transactionType = fieldSetFlags()[12] ? this.transactionType : (CharSequence) defaultValue(fields()[12]);
        record.tokenId = fieldSetFlags()[13] ? this.tokenId : (CharSequence) defaultValue(fields()[13]);
        record.orderDate = fieldSetFlags()[14] ? this.orderDate : (CharSequence) defaultValue(fields()[14]);
        record.completionDate = fieldSetFlags()[15] ? this.completionDate : (CharSequence) defaultValue(fields()[15]);
        record.expectedCompletionDate = fieldSetFlags()[16] ? this.expectedCompletionDate : (CharSequence) defaultValue(fields()[16]);
        record.trackingNumber = fieldSetFlags()[17] ? this.trackingNumber : (CharSequence) defaultValue(fields()[17]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
